// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ethtx.proto

package bsc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProtoCompleteTransaction struct {
	BlockNumber          uint32                                `protobuf:"varint,1,opt,name=BlockNumber,proto3" json:"BlockNumber,omitempty"`
	BlockTime            uint64                                `protobuf:"varint,2,opt,name=BlockTime,proto3" json:"BlockTime,omitempty"`
	Tx                   *ProtoCompleteTransaction_TxType      `protobuf:"bytes,3,opt,name=Tx,proto3" json:"Tx,omitempty"`
	Receipt              *ProtoCompleteTransaction_ReceiptType `protobuf:"bytes,4,opt,name=Receipt,proto3" json:"Receipt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *ProtoCompleteTransaction) Reset()         { *m = ProtoCompleteTransaction{} }
func (m *ProtoCompleteTransaction) String() string { return proto.CompactTextString(m) }
func (*ProtoCompleteTransaction) ProtoMessage()    {}
func (*ProtoCompleteTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2f442129bfe185c, []int{0}
}

func (m *ProtoCompleteTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoCompleteTransaction.Unmarshal(m, b)
}
func (m *ProtoCompleteTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoCompleteTransaction.Marshal(b, m, deterministic)
}
func (m *ProtoCompleteTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoCompleteTransaction.Merge(m, src)
}
func (m *ProtoCompleteTransaction) XXX_Size() int {
	return xxx_messageInfo_ProtoCompleteTransaction.Size(m)
}
func (m *ProtoCompleteTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoCompleteTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoCompleteTransaction proto.InternalMessageInfo

func (m *ProtoCompleteTransaction) GetBlockNumber() uint32 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

func (m *ProtoCompleteTransaction) GetBlockTime() uint64 {
	if m != nil {
		return m.BlockTime
	}
	return 0
}

func (m *ProtoCompleteTransaction) GetTx() *ProtoCompleteTransaction_TxType {
	if m != nil {
		return m.Tx
	}
	return nil
}

func (m *ProtoCompleteTransaction) GetReceipt() *ProtoCompleteTransaction_ReceiptType {
	if m != nil {
		return m.Receipt
	}
	return nil
}

type ProtoCompleteTransaction_TxType struct {
	AccountNonce         uint64   `protobuf:"varint,1,opt,name=AccountNonce,proto3" json:"AccountNonce,omitempty"`
	GasPrice             []byte   `protobuf:"bytes,2,opt,name=GasPrice,proto3" json:"GasPrice,omitempty"`
	GasLimit             uint64   `protobuf:"varint,3,opt,name=GasLimit,proto3" json:"GasLimit,omitempty"`
	Value                []byte   `protobuf:"bytes,4,opt,name=Value,proto3" json:"Value,omitempty"`
	Payload              []byte   `protobuf:"bytes,5,opt,name=Payload,proto3" json:"Payload,omitempty"`
	Hash                 []byte   `protobuf:"bytes,6,opt,name=Hash,proto3" json:"Hash,omitempty"`
	To                   []byte   `protobuf:"bytes,7,opt,name=To,proto3" json:"To,omitempty"`
	From                 []byte   `protobuf:"bytes,8,opt,name=From,proto3" json:"From,omitempty"`
	TransactionIndex     uint32   `protobuf:"varint,9,opt,name=TransactionIndex,proto3" json:"TransactionIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoCompleteTransaction_TxType) Reset()         { *m = ProtoCompleteTransaction_TxType{} }
func (m *ProtoCompleteTransaction_TxType) String() string { return proto.CompactTextString(m) }
func (*ProtoCompleteTransaction_TxType) ProtoMessage()    {}
func (*ProtoCompleteTransaction_TxType) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2f442129bfe185c, []int{0, 0}
}

func (m *ProtoCompleteTransaction_TxType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoCompleteTransaction_TxType.Unmarshal(m, b)
}
func (m *ProtoCompleteTransaction_TxType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoCompleteTransaction_TxType.Marshal(b, m, deterministic)
}
func (m *ProtoCompleteTransaction_TxType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoCompleteTransaction_TxType.Merge(m, src)
}
func (m *ProtoCompleteTransaction_TxType) XXX_Size() int {
	return xxx_messageInfo_ProtoCompleteTransaction_TxType.Size(m)
}
func (m *ProtoCompleteTransaction_TxType) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoCompleteTransaction_TxType.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoCompleteTransaction_TxType proto.InternalMessageInfo

func (m *ProtoCompleteTransaction_TxType) GetAccountNonce() uint64 {
	if m != nil {
		return m.AccountNonce
	}
	return 0
}

func (m *ProtoCompleteTransaction_TxType) GetGasPrice() []byte {
	if m != nil {
		return m.GasPrice
	}
	return nil
}

func (m *ProtoCompleteTransaction_TxType) GetGasLimit() uint64 {
	if m != nil {
		return m.GasLimit
	}
	return 0
}

func (m *ProtoCompleteTransaction_TxType) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *ProtoCompleteTransaction_TxType) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *ProtoCompleteTransaction_TxType) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *ProtoCompleteTransaction_TxType) GetTo() []byte {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *ProtoCompleteTransaction_TxType) GetFrom() []byte {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *ProtoCompleteTransaction_TxType) GetTransactionIndex() uint32 {
	if m != nil {
		return m.TransactionIndex
	}
	return 0
}

type ProtoCompleteTransaction_ReceiptType struct {
	GasUsed              []byte                                          `protobuf:"bytes,1,opt,name=GasUsed,proto3" json:"GasUsed,omitempty"`
	Status               []byte                                          `protobuf:"bytes,2,opt,name=Status,proto3" json:"Status,omitempty"`
	Log                  []*ProtoCompleteTransaction_ReceiptType_LogType `protobuf:"bytes,3,rep,name=Log,proto3" json:"Log,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                        `json:"-"`
	XXX_unrecognized     []byte                                          `json:"-"`
	XXX_sizecache        int32                                           `json:"-"`
}

func (m *ProtoCompleteTransaction_ReceiptType) Reset()         { *m = ProtoCompleteTransaction_ReceiptType{} }
func (m *ProtoCompleteTransaction_ReceiptType) String() string { return proto.CompactTextString(m) }
func (*ProtoCompleteTransaction_ReceiptType) ProtoMessage()    {}
func (*ProtoCompleteTransaction_ReceiptType) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2f442129bfe185c, []int{0, 1}
}

func (m *ProtoCompleteTransaction_ReceiptType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoCompleteTransaction_ReceiptType.Unmarshal(m, b)
}
func (m *ProtoCompleteTransaction_ReceiptType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoCompleteTransaction_ReceiptType.Marshal(b, m, deterministic)
}
func (m *ProtoCompleteTransaction_ReceiptType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoCompleteTransaction_ReceiptType.Merge(m, src)
}
func (m *ProtoCompleteTransaction_ReceiptType) XXX_Size() int {
	return xxx_messageInfo_ProtoCompleteTransaction_ReceiptType.Size(m)
}
func (m *ProtoCompleteTransaction_ReceiptType) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoCompleteTransaction_ReceiptType.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoCompleteTransaction_ReceiptType proto.InternalMessageInfo

func (m *ProtoCompleteTransaction_ReceiptType) GetGasUsed() []byte {
	if m != nil {
		return m.GasUsed
	}
	return nil
}

func (m *ProtoCompleteTransaction_ReceiptType) GetStatus() []byte {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ProtoCompleteTransaction_ReceiptType) GetLog() []*ProtoCompleteTransaction_ReceiptType_LogType {
	if m != nil {
		return m.Log
	}
	return nil
}

type ProtoCompleteTransaction_ReceiptType_LogType struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	Topics               [][]byte `protobuf:"bytes,3,rep,name=Topics,proto3" json:"Topics,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoCompleteTransaction_ReceiptType_LogType) Reset() {
	*m = ProtoCompleteTransaction_ReceiptType_LogType{}
}
func (m *ProtoCompleteTransaction_ReceiptType_LogType) String() string {
	return proto.CompactTextString(m)
}
func (*ProtoCompleteTransaction_ReceiptType_LogType) ProtoMessage() {}
func (*ProtoCompleteTransaction_ReceiptType_LogType) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2f442129bfe185c, []int{0, 1, 0}
}

func (m *ProtoCompleteTransaction_ReceiptType_LogType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoCompleteTransaction_ReceiptType_LogType.Unmarshal(m, b)
}
func (m *ProtoCompleteTransaction_ReceiptType_LogType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoCompleteTransaction_ReceiptType_LogType.Marshal(b, m, deterministic)
}
func (m *ProtoCompleteTransaction_ReceiptType_LogType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoCompleteTransaction_ReceiptType_LogType.Merge(m, src)
}
func (m *ProtoCompleteTransaction_ReceiptType_LogType) XXX_Size() int {
	return xxx_messageInfo_ProtoCompleteTransaction_ReceiptType_LogType.Size(m)
}
func (m *ProtoCompleteTransaction_ReceiptType_LogType) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoCompleteTransaction_ReceiptType_LogType.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoCompleteTransaction_ReceiptType_LogType proto.InternalMessageInfo

func (m *ProtoCompleteTransaction_ReceiptType_LogType) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *ProtoCompleteTransaction_ReceiptType_LogType) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ProtoCompleteTransaction_ReceiptType_LogType) GetTopics() [][]byte {
	if m != nil {
		return m.Topics
	}
	return nil
}

func init() {
	proto.RegisterType((*ProtoCompleteTransaction)(nil), "bsc.ProtoCompleteTransaction")
	proto.RegisterType((*ProtoCompleteTransaction_TxType)(nil), "bsc.ProtoCompleteTransaction.TxType")
	proto.RegisterType((*ProtoCompleteTransaction_ReceiptType)(nil), "bsc.ProtoCompleteTransaction.ReceiptType")
	proto.RegisterType((*ProtoCompleteTransaction_ReceiptType_LogType)(nil), "bsc.ProtoCompleteTransaction.ReceiptType.LogType")
}

func init() { proto.RegisterFile("ethtx.proto", fileDescriptor_b2f442129bfe185c) }

var fileDescriptor_b2f442129bfe185c = []byte{
	// 396 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xdf, 0x8a, 0xd4, 0x30,
	0x14, 0xc6, 0xe9, 0x9f, 0x99, 0xd9, 0x3d, 0xad, 0x22, 0x41, 0x24, 0x0c, 0x5e, 0x94, 0xc5, 0x8b,
	0xea, 0x45, 0xc1, 0xd5, 0x17, 0x58, 0x47, 0x5c, 0x85, 0x61, 0x1d, 0x62, 0xf4, 0x3e, 0x4d, 0xc3,
	0x6e, 0xb1, 0x6d, 0x4a, 0x93, 0x42, 0xf7, 0x8d, 0x7c, 0x21, 0xdf, 0xc5, 0x4b, 0xc9, 0x69, 0x3a,
	0x8e, 0x88, 0xe2, 0xdd, 0xf9, 0x7d, 0x73, 0xbe, 0xc9, 0xf7, 0x25, 0x85, 0x44, 0xd9, 0x3b, 0x3b,
	0x15, 0xfd, 0xa0, 0xad, 0x26, 0x51, 0x69, 0xe4, 0xc5, 0xb7, 0x15, 0xd0, 0x83, 0xc3, 0x9d, 0x6e,
	0xfb, 0x46, 0x59, 0xc5, 0x07, 0xd1, 0x19, 0x21, 0x6d, 0xad, 0x3b, 0x92, 0x41, 0xf2, 0xa6, 0xd1,
	0xf2, 0xeb, 0xcd, 0xd8, 0x96, 0x6a, 0xa0, 0x41, 0x16, 0xe4, 0x0f, 0xd8, 0xa9, 0x44, 0x9e, 0xc2,
	0x39, 0x22, 0xaf, 0x5b, 0x45, 0xc3, 0x2c, 0xc8, 0x63, 0xf6, 0x4b, 0x20, 0xaf, 0x21, 0xe4, 0x13,
	0x8d, 0xb2, 0x20, 0x4f, 0x2e, 0x9f, 0x15, 0xa5, 0x91, 0xc5, 0xdf, 0x8e, 0x2a, 0xf8, 0xc4, 0xef,
	0x7b, 0xc5, 0x42, 0x3e, 0x91, 0x1d, 0x6c, 0x98, 0x92, 0xaa, 0xee, 0x2d, 0x8d, 0xd1, 0xfa, 0xfc,
	0xdf, 0x56, 0xbf, 0x8c, 0xfe, 0xc5, 0xb9, 0xfd, 0x11, 0xc0, 0x7a, 0xfe, 0x4f, 0x72, 0x01, 0xe9,
	0x95, 0x94, 0x7a, 0xec, 0xec, 0x8d, 0xee, 0xa4, 0xc2, 0x1a, 0x31, 0xfb, 0x4d, 0x23, 0x5b, 0x38,
	0xbb, 0x16, 0xe6, 0x30, 0xd4, 0x72, 0xae, 0x91, 0xb2, 0x23, 0xfb, 0xdf, 0xf6, 0x75, 0x5b, 0x5b,
	0xec, 0x12, 0xb3, 0x23, 0x93, 0xc7, 0xb0, 0xfa, 0x22, 0x9a, 0x51, 0x61, 0xd2, 0x94, 0xcd, 0x40,
	0x28, 0x6c, 0x0e, 0xe2, 0xbe, 0xd1, 0xa2, 0xa2, 0x2b, 0xd4, 0x17, 0x24, 0x04, 0xe2, 0xf7, 0xc2,
	0xdc, 0xd1, 0x35, 0xca, 0x38, 0x93, 0x87, 0x10, 0x72, 0x4d, 0x37, 0xa8, 0x84, 0x5c, 0xbb, 0x9d,
	0x77, 0x83, 0x6e, 0xe9, 0xd9, 0xbc, 0xe3, 0x66, 0xf2, 0x02, 0x1e, 0x9d, 0x54, 0xfe, 0xd0, 0x55,
	0x6a, 0xa2, 0xe7, 0xf8, 0x1c, 0x7f, 0xe8, 0xdb, 0xef, 0x01, 0x24, 0x27, 0x77, 0xe2, 0xd2, 0x5c,
	0x0b, 0xf3, 0xd9, 0xa8, 0x0a, 0xab, 0xa7, 0x6c, 0x41, 0xf2, 0x04, 0xd6, 0x9f, 0xac, 0xb0, 0xa3,
	0xf1, 0x9d, 0x3d, 0x91, 0x1d, 0x44, 0x7b, 0x7d, 0x4b, 0xa3, 0x2c, 0xca, 0x93, 0xcb, 0x97, 0xff,
	0x7d, 0xfb, 0xc5, 0x5e, 0xdf, 0xe2, 0x2b, 0x38, 0xf7, 0xf6, 0x23, 0x6c, 0x3c, 0xbb, 0x04, 0x57,
	0x55, 0x35, 0x28, 0x63, 0x96, 0x04, 0x1e, 0x5d, 0xd7, 0xb7, 0xc2, 0x0a, 0x7f, 0x3e, 0xce, 0x2e,
	0x15, 0xd7, 0x7d, 0x2d, 0x0d, 0x06, 0x48, 0x99, 0xa7, 0x72, 0x8d, 0x9f, 0xed, 0xab, 0x9f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x06, 0xd3, 0x2b, 0x69, 0xc5, 0x02, 0x00, 0x00,
}
